# Generated by Django 4.0.6 on 2022-07-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('price_per_day', models.FloatField(max_length=10, null=True)),
                ('occupant_amount', models.CharField(max_length=100, null=True)),
                ('baggage_amount', models.CharField(max_length=100, null=True)),
                ('driver_age', models.FloatField(max_length=10, null=True)),
                ('Power', models.FloatField(max_length=10, null=True)),
                ('door_amount', models.FloatField(max_length=10, null=True)),
                ('acriss_code', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
