# Generated by Django 4.0.6 on 2022-07-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_city_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateTimeField(null=True)),
                ('dropoff_date', models.DateTimeField(null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.car')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_city', to='base.city')),
                ('city1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_city', to='base.city')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_station', to='base.station')),
                ('station1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='base.station')),
            ],
        ),
    ]
