# Generated by Django 4.0.6 on 2022-07-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_car_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
