# Generated by Django 4.0.6 on 2022-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_station_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
